import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/shared/Header";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-fit min-h-screen bg-white pb-12 m-0 p-0 box-border mx-auto">
          <Toaster
            position="bottom-right"
            toastOptions={{
              className: "",
              style: {
                fontSize: "12px",
              },
            }}
          />
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
