import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/shared/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-full m-0 p-0 box-border mx-auto">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
